// Files that contain project-specific content and should never be blindly overwritten.
// All paths are relative to the PROJECT ROOT (not .claude/).
var PROTECTED_FILES = [
  // Project CLAUDE.md (user may have their own)
  'CLAUDE.md',

  // Agent knowledge bases (populated per-project by /evolve and architect-agent RECORD)
  '.claude/agents/architect-agent/index.md',
  '.claude/agents/architect-agent/shared/patterns.md',
  '.claude/agents/architect-agent/decisions/log.md',

  // Tester agent project-specific config
  '.claude/agents/tester-agent/test-patterns.md',
  '.claude/agents/tester-agent/auth-state.md',

  // Mobile tester project-specific config
  '.claude/agents/mobile-tester-agent/screen-patterns.md',

  // Project-specific code patterns (generated by /create-rules)
  '.claude/references/code-patterns.md',

  // Project-specific settings and permissions
  '.claude/settings.local.json',
];

// Directories with project-specific content (architect-agent module knowledge).
// All paths are relative to the PROJECT ROOT.
var PROTECTED_DIRS = [
  '.claude/agents/architect-agent/modules',
  '.claude/agents/architect-agent/frontend',
];

// Files that users commonly customize (rules, hooks).
// These get special "merge" treatment — ask user what to do.
// All paths are relative to the PROJECT ROOT.
var CUSTOMIZABLE_FILES = [
  '.claude/rules/_global.md',
  '.claude/rules/backend.md',
  '.claude/rules/frontend.md',
  '.claude/rules/mobile.md',
  '.claude/rules/database.md',
  '.claude/rules/testing.md',
  '.claude/hooks/branch-guard.sh',
  '.claude/hooks/plan-required.sh',
  '.claude/hooks/architect-sync.sh',
  '.claude/hooks/evolve-reminder.sh',
  '.claude/hooks/session-primer.sh',
];

// Helper: normalize a path to project-root-relative format.
// Call sites that compare against these lists MUST use this function
// to ensure the path prefix matches (e.g., '.claude/rules/backend.md').
function toProjectRelative(filePath, rootDir) {
  var path = require('path');
  var abs = path.resolve(filePath);
  var root = path.resolve(rootDir);
  return path.relative(root, abs).split(path.sep).join('/');
}

module.exports = {
  PROTECTED_FILES: PROTECTED_FILES,
  PROTECTED_DIRS: PROTECTED_DIRS,
  CUSTOMIZABLE_FILES: CUSTOMIZABLE_FILES,
  toProjectRelative: toProjectRelative,
};
